### ISSUE TITLE
Unable to run PurgeCSS due to CssSyntaxError

### ISSUE THREAD

**Issue by alphametric** [spatie/laravel-mix-purgecss#74]
After recently upgrading my NPM packages (specifically Tailwind CSS to v1.1), I encounter the following problem when running a production build through Laravel Mix:

```
CssSyntaxError: <css input>:162114:23: Unknown word
    at Input.error (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/postcss/lib/input.js:130:16)
    at Parser.unknownWord (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/postcss/lib/parser.js:563:22)
    at Parser.other (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/postcss/lib/parser.js:168:12)
    at Parser.parse (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/postcss/lib/parser.js:77:16)
    at Function.parse (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/postcss/lib/parse.js:17:12)
    at Purgecss.getCssContents (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/purgecss/lib/purgecss.js:478:31)
    at Purgecss.purge (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/purgecss/lib/purgecss.js:443:19)
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/purgecss-webpack-plugin/lib/purgecss-webpack-plugin.js:282:33
    at Array.forEach (<anonymous>)
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/purgecss-webpack-plugin/lib/purgecss-webpack-plugin.js:247:23
    at Array.forEach (<anonymous>)
    at PurgecssPlugin.runPluginHook (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/purgecss-webpack-plugin/lib/purgecss-webpack-plugin.js:235:26)
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/purgecss-webpack-plugin/lib/purgecss-webpack-plugin.js:219:18
    at _next0 (eval at create (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at eval (eval at create (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/extract-text-webpack-plugin/dist/index.js:330:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/webpack/lib/Compilation.js:1367:32
    at eval (eval at create (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/extract-text-webpack-plugin/dist/index.js:296:11
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/async/dist/async.js:1064:13)
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/async/dist/async.js:969:16
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/extract-text-webpack-plugin/dist/index.js:274:13
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/async/dist/async.js:1064:13)
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/async/dist/async.js:969:16
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/extract-text-webpack-plugin/dist/index.js:261:26
    at callback (/Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/webpack/lib/Compilation.js:1186:5)
    at /Users/**REDACTED**/Documents/Code/Apps/**REDACTED**/node_modules/webpack/lib/Compilation.js:1209:5
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

Just to confirm, the issue only occurs on production builds (where PurgeCSS is being applied).

Is it possible to determine which "unknown word" is causing the problem?

Thanks!

**Comment by axtg** [comment]
I'd love to hear what made you close this issue. I'm running into the same problem.

**Comment by mattkingshott** [comment]
Don’t remember to be honest. Try upgrading all packages. Usually does the job...
